### ISSUE TITLE
Another way to do Proof of Elapsed Time (PoET)?

### ISSUE THREAD

**Issue by ttmc** [hyperledger/hyperledger#18]
I see that Intel has made their Distributed Ledger project open now, at https://github.com/intelledger

One of the consensus algorithms it can use is what they call Proof of Elapsed Time (PoET), which is a variation on Nakamoto consensus, where the proof of elapsed time comes from special security-hardened Intel hardware. That makes mining much cheaper, and it also gives people an incentive to buy that Intel hardware. It's clever.

There are other ways to get a proof of elapsed time. One way is to take advantage of the fact that the speed of light it finite. If you have a message (e.g. the hash of the block at the end of the longest blockchain) and you send it to a computer on the Moon, there's some minimum amount of time that that can take: the current distance to the Moon divided by the speed of light. That time is typically a bit more than one second. The computer on the Moon could sign the message using it's private signing key and send the message back to Earth. It's easy to verify that the message was, in fact, signed by the computer on the Moon (using the public verifying key), and therefore that some minimum amount of time must have passed between the creation of the original message and the receipt of the signed message.

If you want to make the required elapsed time twice as long, you can require the participant to sign the message received from the Moon (with their private key), send that back to the Moon to be signed by the computer on the Moon, and wait for the signed message from the Moon.

That method can be used to require arbitrarily many round trips. One hundred round trips would take more than 230 seconds (more than 3.5 minutes), not counting the time required to do the signing.

Lastly, the required number of round trips can be randomized per participant by requiring the signed message (or a hash of it) to meet some less-than criterion similar to the Nakamoto puzzle. Received signed messages will be different for different participants because they all have different private signing keys. (That could be made true even for one round trip by requiring the participant to sign the original hash before sending it to the Moon.)

**Comment by manishjhawar** [comment]
Would that not make the scheme depend upon a single computer on the moon?

**Comment by ttmc** [comment]
I suppose there could be multiple computers on the Moon, Antarctica, orbiting satellites, and (insert interesting place here). So long as you know where it is (and its public key), you can know the minimum round-trip communication times.

**Comment by zhangguangfeng** [comment]
Hardware security module(HSM,for example:Eracom) can provide a trusted time to proof.

**Comment by ttmc** [comment]
"Hardware security module(HSM,for example:Eracom) can provide a trusted time to proof."

Yes, I know. I was inspired to think about ways to do proof of elapsed time by Intel's recent proposal, which includes the hardware security module method. My question is simple: Are there _other_ ways to get a proof of elapsed time?

Let's explore the space of possibilities.

**Comment by zhangguangfeng** [comment]
Are there other ways to get a proof of elapsed time?This is a good question, because I am doing consortium blockchains for banks, and the bank has a ready-made HSM, so I do not consciously think of it.

**Comment by drgorb** [comment]
There is no way to prove that the computer on the moon has not been moved. Failing that proof, there is no difference with creating a permissioned network and having the computer on the moon simply sign your transactions.

**Comment by christo4ferris** [comment]
This doesn't appear to be an issue so much as discussion of a hypothetical. Closing this - please feel free to continue via another medium (slack, mailing list etc)

**Comment by hay-wire** [comment]
@ttmc Interesting! Were you guys able continue this discussion later? I'm interested in reading more of it. :)

**Comment by msand** [comment]
How about maintaining a set of distributed communicating observers with public/private keys, and two phases of competition. 
One phase to find the approximate distance matrices for m clusters of k nearest neighbors (smallest latency).
Another phase to get a globally distributed chain of signatures. requiring some threshold of total round trip time and cluster distribution, relative to network and block commit size.

Clustering would be based on finding geographically similarly located places, to get membership in a cluster one needs sufficiently low latency to k neighbors. If the latency is above the communication limit, one cannot take part in the consensus signature chain.

Once sufficiently many clusters have been recognized, a chain across the clusters is calculated, based on a hash of the transactions in the block and the distance matrices. Then the hash is signed, by at least one member of each chosen cluster, in the order specified by the chain.

A peer can be a member of at most c clusters, the signature chain must be acyclic, and connections can only be within clusters, relayed by being member of both sending and receiving clusters.

I would call this Proof of Communication or Proof of Witness. Rather than proof of time. Distributed latency using competition for membership by pressing it down, and then requiring a long enough chain with sufficient distribution in the network of active witnesses, to make it hard to fake.

**Comment by msand** [comment]
When I think about it, Proof of Communicating Witnesses seems the capture the core idea of finding the fastest communicating witnesses, and having them sign the hash of the new block. The competition for membership in clusters would going on continuously. Once per timecycle of e.g. 10 seconds (or some multiple of round-trips around the globe at light speed), the published transactions are aggregated to the timeslot they were published and sufficiently (globally) propagated within. Once the block has been signed by a sufficiently large chain, it then (the chain with largest network coverage/time taken) becomes the basis for the next block, and the witnesses are rewarded for their communication and signature calculation with Wits or WitCoin (Witness proof tokens).
