### ISSUE TITLE
Communication Error When Enable TLS in Peer Restful API

### ISSUE THREAD

**Issue by billsg** [hyperledger/hyperledger#49]
In order to protect the safety of validating node, I have set the "# TLS Settings for p2p communications tls - enabled"  to true, using the cert and key generated by openssl.

I 'm able to start membership service and validating node. However, when I tried to deploy chain code "cp_chaincode_v2" ,  following error is shown:

---------------Validating Node Message------------
ServerHandshake 10.160.1.122:44251 failed:  tls: first record does not look like a TLS handshake
grpc: Server.Serve failed to complete security handshake.

----------------Chain code Message -------------------
10:41:10.395 [shim] DEBU : Peer address: 10.160.1.122:30303
10:41:10.426 [shim] ERRO : Error trying to connect to local peer: grpc: timed out trying to connect
Error starting Simple chaincode: %s Error trying to connect to local peer: grpc: timed out trying to connect

Once I disable the tls, everything will go back to normal.

**Comment by christo4ferris** [comment]
@billsg we are using JIRA to track issues for the Hyperledger fabric project. You'll need a Linux ID (free) at [identity.linuxfoundation.org](https://identity.linuxfoundation.org/) and can post/track issues at [jira.hyperledger.org](http://jira.hyperledger.org).

**Comment by shanlusun** [comment]
Does the issue resolved ？ got the same issue now， need help！

**Comment by shanlusun** [comment]
The issue is resolved.

Fix the config in peer-base.yaml:
- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=channel_default # Very important, must be set to the same folder name(folderName_default) where running the docker-compose command

In my case I am starting the docker-compose-cli.yaml in 'channel' folder.
The root cause is that the new container created like ' dev-peer0.org1.example.com-*-v0' can't connect to local peer because they are not in the same docker network if you using the default setting:
- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=e2ecli_default
